Milestone102
lailaeliotti1/HOME_FBU pull request #13
Opened 2022-06-24 18:40 UTC by lailaeliotti1

2022-06-27 22:05 UTC, RicardoLH requested changes

2022-06-27 22:05 UTC, RicardoLH commented on app/src/main/java/com/example/home/login/LoginActivity.java
> +        Log.i(TAG, "Attempting to login user " + username + " " + password);
Not a very good idea to log username + password. Let's remove this

2022-06-27 22:05 UTC, RicardoLH commented on app/src/main/java/com/example/home/login/LoginActivity.java
> +                    Toast.makeText(LoginActivity.this, e.getMessage(), Toast.LENGTH_SHORT).show();
instead of showing a toast with the exeption message, can't we show a user friendly message?

2022-06-27 23:15 UTC, lailaeliotti1 commented on app/src/main/java/com/example/home/MainActivity.java
>  public class MainActivity extends AppCompatActivity {
I thought I needed it to access bottomNavigation bar

2022-06-28 00:38 UTC, RicardoLH approved these changes

2022-06-28 00:38 UTC, RicardoLH commented on app/src/main/java/com/example/home/models/User.java
> +    public UserPreferences getUserPreferences(){return mUserPreferences;}
Let's have this in separate lines. Same below

2022-06-28 16:37 UTC, merged